CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid (),
  chat_id BIGINT NOT NULL,
  is_sending BOOLEAN NOT NULL DEFAULT FALSE,
  recipient_id UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  allow_text BOOLEAN NOT NULL DEFAULT TRUE,
  allow_sticker BOOLEAN NOT NULL DEFAULT TRUE,
  allow_gif BOOLEAN NOT NULL DEFAULT TRUE,
  allow_photo BOOLEAN NOT NULL DEFAULT TRUE,
  allow_video BOOLEAN NOT NULL DEFAULT TRUE,
  allow_voice BOOLEAN NOT NULL DEFAULT TRUE,
  allow_audio BOOLEAN NOT NULL DEFAULT TRUE,
  allow_document BOOLEAN NOT NULL DEFAULT TRUE,
  blocks BIGINT[] NOT NULL DEFAULT '{}'
);
