CREATE TABLE IF NOT EXISTS users (
  serial SERIAL PRIMARY KEY,
  id UUID DEFAULT gen_random_uuid (),
  chat_id BIGINT NOT NULL,
  is_sending BOOLEAN NOT NULL DEFAULT FALSE,
  recipient_id UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  allow_text BOOLEAN NOT NULL DEFAULT TRUE,
  allow_sticker BOOLEAN NOT NULL DEFAULT FALSE,
  allow_gif BOOLEAN NOT NULL DEFAULT FALSE,
  allow_photo BOOLEAN NOT NULL DEFAULT FALSE,
  allow_video BOOLEAN NOT NULL DEFAULT FALSE,
  allow_voice BOOLEAN NOT NULL DEFAULT FALSE,
  allow_audio BOOLEAN NOT NULL DEFAULT FALSE,
  allow_document BOOLEAN NOT NULL DEFAULT FALSE,
  blocks BIGINT[] NOT NULL DEFAULT '{}',
  is_ban BOOLEAN NOT NULL DEFAULT FALSE,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE
);
