// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"fa_IR": &dictionary{index: fa_IRIndex, data: fa_IRData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Audio":                            12,
	"Blocked succesfully! 🔒✅":          26,
	"Document":                         13,
	"Gif":                              8,
	"Photo":                            9,
	"Send your message ✏️:":            24,
	"Sticker":                          7,
	"Text":                             6,
	"Unblocked successfully! 🔓✅":       27,
	"Video":                            10,
	"Voice":                            11,
	"You are not in sending mode... ⛔": 17,
	"You blocked by the user you're trying to send the message! 🔒😿":               18,
	"Your message sended successfully! 📨😍":                                        23,
	"Your message type is limited by reciever or isn't supported by this bot. 🔒🥹": 22,
	"about_message":                         16,
	"message_restrictions_settings_message": 15,
	"settings_message":                      5,
	"start_message":                         3,
	"ℹ️ About":                              0,
	"⚙️ Settings":                           1,
	"⬅️ Back":                               14,
	"💬 Reply":                               19,
	"🔒 Block":                               20,
	"🔓 Unblock":                             25,
	"🔗 Get Hidden Link":                     2,
	"🚨 Report":                              21,
	"🚫 Message Restrictions":                4,
}

var en_USIndex = []uint32{ // 29 elements
	0x00000000, 0x0000000d, 0x0000001d, 0x00000032,
	0x00000155, 0x0000016f, 0x00000206, 0x0000020b,
	0x00000213, 0x00000217, 0x0000021d, 0x00000223,
	0x00000229, 0x0000022f, 0x00000238, 0x00000244,
	0x00000293, 0x0000039a, 0x000003bd, 0x00000401,
	0x0000040c, 0x00000417, 0x00000423, 0x00000475,
	0x000004a0, 0x000004ba, 0x000004c7, 0x000004e4,
	0x00000504,
} // Size: 140 bytes

const en_USData string = "" + // Size: 1284 bytes
	"\x02ℹ️ About\x02⚙️ Settings\x02🔗 Get Hidden Link\x02Hello 👋, Welcome to " +
	"*Hidden Chat Bot*!🥰\x0a\x0aYou can create hidden chat links and others c" +
	"an send you messages without knowing your username😻😻.\x0a\x0aJust click " +
	"on *\x22🔗 Get Hidden Link\x22* button and paste your link in your social" +
	" media to start recieving wonderful messages👻🤡🙈!\x02🚫 Message Restrictio" +
	"ns\x02Here is your account control center! 🛠️🪛🙆\x0a\x0aYou can change yo" +
	"ur hidden link 🔗, set allowed/disallowed message types ✅❌ and more! 😇" +
	"\x02Text\x02Sticker\x02Gif\x02Photo\x02Video\x02Voice\x02Audio\x02Docume" +
	"nt\x02⬅️ Back\x02You can set what type of messages you want to recieve o" +
	"r not from others! 💯\x02Create *hidden chat links* to send messages with" +
	"out revealing your username. 🔒\x0aShare your link, stay anonymous, and e" +
	"njoy private conversations. 💬\x0aYour identity remains secure while you " +
	"chat freely. 👻\x0a\x0aLet’s keep your chats secret and fun! 🤖✨🎉\x02You a" +
	"re not in sending mode... ⛔\x02You blocked by the user you're trying to " +
	"send the message! 🔒😿\x02💬 Reply\x02🔒 Block\x02🚨 Report\x02Your message t" +
	"ype is limited by reciever or isn't supported by this bot. 🔒🥹\x02Your me" +
	"ssage sended successfully! 📨😍\x02Send your message ✏️:\x02🔓 Unblock\x02B" +
	"locked succesfully! 🔒✅\x02Unblocked successfully! 🔓✅"

var fa_IRIndex = []uint32{ // 29 elements
	0x00000000, 0x00000019, 0x0000002f, 0x00000053,
	0x0000023e, 0x00000262, 0x00000355, 0x0000035c,
	0x00000369, 0x00000370, 0x00000377, 0x00000380,
	0x00000387, 0x0000038e, 0x00000397, 0x000003ab,
	0x00000437, 0x000005b8, 0x00000600, 0x0000065a,
	0x00000668, 0x00000676, 0x00000686, 0x00000741,
	0x00000778, 0x00000798, 0x000007aa, 0x000007d3,
	0x00000800,
} // Size: 140 bytes

const fa_IRData string = "" + // Size: 2048 bytes
	"\x02ℹ️ درباره ما\x02⚙️ تنظیمات\x02🔗 دریافت لینک پیام\x02سلام 👋، به *بات " +
	"چت ناشناس* خوش اومدی!🥰\x0a\x0aاینجا میتونی لینک چت ناشناس بسازی و بقیه " +
	"بدون اینکه یوزرنیم تو رو بدونن بهت پیام بدن😻😻.\x0a\x0aفقط کافیه روی دکم" +
	"ه *«🔗 دریافت لینک پیام»* کلیک کنی و لینکتو بگذاری توی شبکه های اجتماعی " +
	"تا شروع کنی به دریافت پیام های شگفت انگیز بقیه👻🤡🙈!\x02🚫 محدودیت های پیا" +
	"م\x02اینجا تنظیمات اکانت توئه! 🛠️🪛🙆\x0a\x0a میتونی لینک پیامتو تغییر بد" +
	"ی 🔗، مشخص کنی چه پیام هایی برات بیان یا نیان ✅❌ و خیلی چیزای بیشتر! 😇" +
	"\x02متن\x02استیکر\x02گیف\x02عکس\x02فیلم\x02ویس\x02صدا\x02فایل\x02➡️ بازگ" +
	"شت\x02اینجا میتونی مشخص کنی چه پیام هایی دوست داری که از بقیه دریافت کن" +
	"ی یا نکنی! 💯\x02*لینک چت ناشناس* بساز و بدون اینکه یوزرنیمت رو به بقیه " +
	"نشون بدی چت کن. 🔒\x0aلینکتو منتشر کن، مخفی بمون و از چت ناشناس لذت ببر." +
	" 💬\x0aدر حالی که راحت چت می کنی، اینکه کی هستی مخفی می مونه. 👻\x0a\x0aبی" +
	"ا چتاتو امن و جالب کنیم! 🤖✨🎉\x02شما در وضعیت ارسال پیام قرار ندارید... " +
	"⛔\x02کاربری که میخوای بهش پیام بفرستی بلاکت کرده! 🔒😿\x02💬 پاسخ\x02🔒 بل" +
	"اک\x02🚨 گزارش\x02دریافت کننده پیام نوع پیامی که میخوای بهش بفرستی رو مح" +
	"دود کرده یا این نوع توسط بات پشتیبانی نمیشه. 🔒🥹\x02پیامت با موفقیت ارسا" +
	"ل شد! 📨😍\x02پیامتو بفرست ✏️:\x02🔓 آنبلاک\x02با موفقیت بلاک شد! 🔒✅\x02با" +
	" موفقیت آنبلاک شد! 🔓✅"

	// Total table size 3612 bytes (3KiB); checksum: AF2DA132
