// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"fa_IR": &dictionary{index: fa_IRIndex, data: fa_IRData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Are you sure you want change the hidden link? Your previous link will be invalid! 🚨🚫": 9,
	"Audio":                      16,
	"Banned succesfully! 🔴✅":     31,
	"Blocked succesfully! 🔒✅":    34,
	"Cancel ❌":                   8,
	"Document":                   17,
	"Gif":                        12,
	"Photo":                      13,
	"Send your message ✏️:":      28,
	"Sticker":                    11,
	"Text":                       10,
	"Unbanned successfully! 🟢✅":  32,
	"Unblocked successfully! 🔓✅": 35,
	"Video":                      14,
	"Voice":                      15,
	"Yes, I'm sure ✅":            7,
	"You are banned by bot's admin and you can't use bot anymore! ⛔❌🔴":            36,
	"You are not in sending mode... ⛔":                                            21,
	"You blocked by the user you're trying to send the message! 🔒😿":               22,
	"Your message sended successfully! 📨😍":                                        27,
	"Your message type is limited by reciever or isn't supported by this bot. 🔒🥹": 26,
	"about_message":                         20,
	"message_restrictions_settings_message": 19,
	"settings_message":                      6,
	"start_message":                         3,
	"ℹ️ About":                              0,
	"⚙️ Settings":                           1,
	"⬅️ Back":                               18,
	"💬 Reply":                               23,
	"🔒 Block":                               24,
	"🔓 Unblock":                             33,
	"🔗 Change Hidden Link":                  4,
	"🔗 Get Hidden Link":                     2,
	"🔴 Ban":                                 29,
	"🚨 Report":                              25,
	"🚫 Message Restrictions":                5,
	"🟢 Unban":                               30,
}

var en_USIndex = []uint32{ // 38 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000d, 0x0000001d, 0x00000032,
	0x00000155, 0x0000016d, 0x00000187, 0x0000021e,
	0x00000230, 0x0000023b, 0x00000296, 0x0000029b,
	0x000002a3, 0x000002a7, 0x000002ad, 0x000002b3,
	0x000002b9, 0x000002bf, 0x000002c8, 0x000002d4,
	0x00000323, 0x0000042a, 0x0000044d, 0x00000491,
	0x0000049c, 0x000004a7, 0x000004b3, 0x00000505,
	0x00000530, 0x0000054a, 0x00000553, 0x0000055e,
	// Entry 20 - 3F
	0x0000057a, 0x00000599, 0x000005a6, 0x000005c3,
	0x000005e3, 0x0000062b,
} // Size: 176 bytes

const en_USData string = "" + // Size: 1579 bytes
	"\x02ℹ️ About\x02⚙️ Settings\x02🔗 Get Hidden Link\x02Hello 👋, Welcome to " +
	"*Hidden Chat Bot*!🥰\x0a\x0aYou can create hidden chat links and others c" +
	"an send you messages without knowing your username😻😻.\x0a\x0aJust click " +
	"on *\x22🔗 Get Hidden Link\x22* button and paste your link in your social" +
	" media to start recieving wonderful messages👻🤡🙈!\x02🔗 Change Hidden Link" +
	"\x02🚫 Message Restrictions\x02Here is your account control center! 🛠️🪛🙆" +
	"\x0a\x0aYou can change your hidden link 🔗, set allowed/disallowed messag" +
	"e types ✅❌ and more! 😇\x02Yes, I'm sure ✅\x02Cancel ❌\x02Are you sure yo" +
	"u want change the hidden link? Your previous link will be invalid! 🚨🚫" +
	"\x02Text\x02Sticker\x02Gif\x02Photo\x02Video\x02Voice\x02Audio\x02Docume" +
	"nt\x02⬅️ Back\x02You can set what type of messages you want to recieve o" +
	"r not from others! 💯\x02Create *hidden chat links* to send messages with" +
	"out revealing your username. 🔒\x0aShare your link, stay anonymous, and e" +
	"njoy private conversations. 💬\x0aYour identity remains secure while you " +
	"chat freely. 👻\x0a\x0aLet’s keep your chats secret and fun! 🤖✨🎉\x02You a" +
	"re not in sending mode... ⛔\x02You blocked by the user you're trying to " +
	"send the message! 🔒😿\x02💬 Reply\x02🔒 Block\x02🚨 Report\x02Your message t" +
	"ype is limited by reciever or isn't supported by this bot. 🔒🥹\x02Your me" +
	"ssage sended successfully! 📨😍\x02Send your message ✏️:\x02🔴 Ban\x02🟢 Unb" +
	"an\x02Banned succesfully! 🔴✅\x02Unbanned successfully! 🟢✅\x02🔓 Unblock" +
	"\x02Blocked succesfully! 🔒✅\x02Unblocked successfully! 🔓✅\x02You are ban" +
	"ned by bot's admin and you can't use bot anymore! ⛔❌🔴"

var fa_IRIndex = []uint32{ // 38 elements
	// Entry 0 - 1F
	0x00000000, 0x00000019, 0x0000002f, 0x00000053,
	0x0000023e, 0x00000260, 0x00000284, 0x00000377,
	0x00000391, 0x0000039c, 0x00000436, 0x0000043d,
	0x0000044a, 0x00000451, 0x00000458, 0x00000461,
	0x00000468, 0x0000046f, 0x00000478, 0x0000048c,
	0x00000518, 0x00000699, 0x000006e1, 0x0000073b,
	0x00000749, 0x00000757, 0x00000767, 0x00000822,
	0x00000859, 0x00000879, 0x00000889, 0x000008a4,
	// Entry 20 - 3F
	0x000008cf, 0x0000090c, 0x0000091e, 0x00000947,
	0x00000974, 0x00000a03,
} // Size: 176 bytes

const fa_IRData string = "" + // Size: 2563 bytes
	"\x02ℹ️ درباره ما\x02⚙️ تنظیمات\x02🔗 دریافت لینک پیام\x02سلام 👋، به *بات " +
	"چت ناشناس* خوش اومدی!🥰\x0a\x0aاینجا میتونی لینک چت ناشناس بسازی و بقیه " +
	"بدون اینکه یوزرنیم تو رو بدونن بهت پیام بدن😻😻.\x0a\x0aفقط کافیه روی دکم" +
	"ه *«🔗 دریافت لینک پیام»* کلیک کنی و لینکتو بگذاری توی شبکه های اجتماعی " +
	"تا شروع کنی به دریافت پیام های شگفت انگیز بقیه👻🤡🙈!\x02🔗 تغییر لینک پیام" +
	"\x02🚫 محدودیت های پیام\x02اینجا تنظیمات اکانت توئه! 🛠️🪛🙆\x0a\x0a میتونی " +
	"لینک پیامتو تغییر بدی 🔗، مشخص کنی چه پیام هایی برات بیان یا نیان ✅❌ و خ" +
	"یلی چیزای بیشتر! 😇\x02آره، مطمئنم ✅\x02لغو ❌\x02مطمئنی میخوای لینک پیام" +
	"تو تغییر بدی؟ اگه اینکارو کنی لینک قبلی دیگه معتبر نیست! 🚨🚫\x02متن\x02ا" +
	"ستیکر\x02گیف\x02عکس\x02فیلم\x02ویس\x02صدا\x02فایل\x02➡️ بازگشت\x02اینجا" +
	" میتونی مشخص کنی چه پیام هایی دوست داری که از بقیه دریافت کنی یا نکنی! 💯" +
	"\x02*لینک چت ناشناس* بساز و بدون اینکه یوزرنیمت رو به بقیه نشون بدی چت ک" +
	"ن. 🔒\x0aلینکتو منتشر کن، مخفی بمون و از چت ناشناس لذت ببر. 💬\x0aدر حالی" +
	" که راحت چت می کنی، اینکه کی هستی مخفی می مونه. 👻\x0a\x0aبیا چتاتو امن و" +
	" جالب کنیم! 🤖✨🎉\x02شما در وضعیت ارسال پیام قرار ندارید... ⛔\x02کاربری که" +
	" میخوای بهش پیام بفرستی بلاکت کرده! 🔒😿\x02💬 پاسخ\x02🔒 بلاک\x02🚨 گزارش" +
	"\x02دریافت کننده پیام نوع پیامی که میخوای بهش بفرستی رو محدود کرده یا ای" +
	"ن نوع توسط بات پشتیبانی نمیشه. 🔒🥹\x02پیامت با موفقیت ارسال شد! 📨😍\x02پی" +
	"امتو بفرست ✏️:\x02🔴 مسدود\x02🟢 رفع مسدودیت\x02با موفقیت مسدود شد! 🔴✅" +
	"\x02با موفقیت از مسدودیت خارج شد! 🟢✅\x02🔓 آنبلاک\x02با موفقیت بلاک شد! 🔒" +
	"✅\x02با موفقیت آنبلاک شد! 🔓✅\x02ادمین بات شما رو مسدود کرده و نمی تونی" +
	"د از این به بعد از بات استفاده کنید! ⛔❌🔴"

	// Total table size 4494 bytes (4KiB); checksum: A97E13FF
